# name: CI

# on:
#   push:
#     branches:
#       - master

# jobs:
#   create-picture-docker-hub:
#     name: build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Read current version
#         id: read_version
#         run: echo "::set-output name=VERSION::$(cat version.txt)"

#       - name: Increment version
#         id: increment_version
#         run: |
#           CURRENT_VERSION=$(echo ${{ steps.read_version.outputs.VERSION }})
#           MAJOR=$(echo $CURRENT_VERSION | cut -d '.' -f 1)
#           MINOR=$(echo $CURRENT_VERSION | cut -d '.' -f 2)
#           PATCH=$(echo $CURRENT_VERSION | cut -d '.' -f 3)
#           PATCH=$((PATCH + 1))
#           echo "::set-output name=VERSION::${MAJOR}.${MINOR}.${PATCH}"

#       - name: Write new version to file
#         run: echo "${{ steps.increment_version.outputs.VERSION }}" > version.txt

#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKER_USER_NAME }}
#           password: ${{ secrets.DOCKER_TOKEN }}

#       - name: Build Docker image
#         uses: docker/build-push-action@v5
#         with:
#           context: .
#           file: ./Dockerfile
#           push: true
#           tags: ${{ secrets.DOCKER_USER_NAME }}/poleit:${{ steps.increment_version.outputs.VERSION }}

name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  create-picture-docker-hub:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get version
        run: |
          echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USER_NAME }}/poleit:${{ env.VERSION }}
      - name: login docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USER_NAME }}/poleit:${{ env.VERSION }}
            ${{ secrets.DOCKER_USER_NAME }}/poleit:latest
