name:  Release

on:
  push:
    tags:
      - '*.*.*' 
  pull_request:
    branches:
      - master

jobs:
  create-picture-docker-hub:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: check build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USER_NAME }}/poleit:${{ github.ref_name }}

      - name: login docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USER_NAME }}/poleit:${{ github.ref_name }}
            ${{ secrets.DOCKER_USER_NAME }}/poleit:latest
